"""
seed_data.py — Pre-seeded demo sessions for the Security Clearance Readiness Advisor.

All Claude responses are pre-baked so the demo works without ANTHROPIC_API_KEY.
Content is educational only, sourced from SEAD 4 and the public Adjudicative Desk Reference.
Nothing here predicts, scores, or assesses any individual.
"""
from __future__ import annotations

import json


DEMO_SESSIONS: list[dict] = [
    {
        "id": 1,
        "session_name": "Entry-Level SECRET — New Graduate",
        "clearance_level": "SECRET",
        "guidelines_selected": json.dumps(["E", "F", "H"]),
        "context_notes": (
            "First clearance application. Recent college graduate, some student loan debt, "
            "experimented with marijuana in college before applying."
        ),
        "claude_briefings": json.dumps({
            "E": (
                "**Guideline E — Personal Conduct**\n\n"
                "Personal Conduct is one of the most broadly applied of the thirteen "
                "adjudicative guidelines, and for good reason: it addresses the core "
                "question of whether an individual is trustworthy and reliable. "
                "Adjudicators are trained to look at overall patterns — not isolated "
                "moments — and the SF-86 form and the Subject Interview are the two "
                "places where Personal Conduct is most directly evaluated.\n\n"
                "The single most important thing to understand about this guideline "
                "is the emphasis on honesty in the security process itself. Deliberately "
                "omitting, misrepresenting, or falsifying information on the SF-86 — "
                "even about something that would not otherwise be disqualifying — is a "
                "serious concern under Guideline E. Adjudicators and investigators are "
                "trained to distinguish between a good-faith error (you forgot a short-term "
                "job from a decade ago) and a deliberate omission. If you are uncertain "
                "whether something should be disclosed, the ADR's consistent advice is: "
                "disclose it. The cover-up is typically more damaging than the underlying fact.\n\n"
                "Beyond the form itself, adjudicators examine whether an individual's "
                "general conduct demonstrates the reliability and sound judgment needed "
                "to protect classified information. This includes whether you follow "
                "through on commitments, whether you associate with people known to be "
                "involved in criminal activity, and whether you have a history of "
                "irresponsible behavior that might suggest you could be exploited.\n\n"
                "The Whole Person Concept is especially central to Guideline E. "
                "A single act of poor judgment does not define a person — adjudicators "
                "weigh frequency, recency, circumstances, and demonstrated rehabilitation. "
                "If you made a mistake in the past, being forthright about it and "
                "demonstrating that your behavior has changed is generally viewed more "
                "favorably than trying to conceal it.\n\n"
                "For a new applicant, the most practical advice from the ADR is straightforward: "
                "read the SF-86 questions carefully, take your time filling them out, and "
                "when in doubt about whether to disclose something, disclose it. "
                "Completeness and honesty set the foundation for everything else."
            ),
            "F": (
                "**Guideline F — Financial Considerations**\n\n"
                "Financial Considerations is one of the most commonly raised adjudicative "
                "guidelines — not because financial difficulty is unusual, but because "
                "financial pressure is one of the historically documented motivators for "
                "espionage and the unauthorized disclosure of classified information. "
                "The concern is not hardship itself: the concern is whether financial "
                "pressure could make someone susceptible to coercion or exploitation.\n\n"
                "Adjudicators are trained to distinguish between two very different "
                "financial situations. The first is financial difficulty caused by "
                "circumstances largely outside an individual's control — a medical "
                "emergency, a job loss, a divorce — combined with responsible behavior "
                "in addressing those difficulties. The second is chronic financial "
                "irresponsibility: a pattern of not meeting obligations despite having "
                "resources, multiple delinquencies, or financial crimes. The ADR "
                "addresses both, but they are weighted very differently.\n\n"
                "Student loan debt, taken on its own, is a financial obligation like "
                "any other. What matters to adjudicators is whether the debt is being "
                "managed responsibly. If you are current on your payments, enrolled in "
                "an income-based repayment plan, or otherwise handling the obligation, "
                "that is exactly the kind of responsible financial behavior the ADR "
                "describes as mitigating. What would raise concern is if the debt is "
                "in default, in collections, or if you have a pattern of ignoring "
                "financial obligations across multiple accounts.\n\n"
                "The ADR explicitly identifies mitigating factors for financial concerns: "
                "the problem was caused by circumstances outside your control, you "
                "recognized the problem and are taking concrete steps to fix it, and "
                "you have a reasonable plan that is being followed. For student loans "
                "specifically, being enrolled in a federal repayment program and staying "
                "current demonstrates exactly that responsible posture.\n\n"
                "The SF-86 asks detailed questions about your financial history, including "
                "delinquencies, bankruptcies, and civil judgments. Answer these completely "
                "and accurately. If there are financial issues in your history, be prepared "
                "to explain the circumstances and what you have done — or are doing — to "
                "address them."
            ),
            "H": (
                "**Guideline H — Drug Involvement and Substance Misuse**\n\n"
                "Drug Involvement is one of the most frequently raised concerns for first-time "
                "clearance applicants, particularly those applying shortly after college. "
                "The guideline addresses illegal drug use and misuse of controlled substances, "
                "and the concern operates on two levels: first, that illegal drug use "
                "demonstrates a willingness to disregard federal law; second, that substance "
                "dependence can create financial pressure, impair judgment, and create "
                "vulnerability to exploitation.\n\n"
                "On marijuana specifically: it is essential to understand that marijuana "
                "remains a Schedule I controlled substance under federal law, regardless "
                "of what any state law says. Adjudicators apply federal law, not state law. "
                "This means that marijuana use is evaluated under Guideline H even in states "
                "where it is legal. The adjudicative guidelines distinguish, however, between "
                "past experimentation and current or recent use, and between occasional use "
                "and habitual use or dependence.\n\n"
                "The ADR describes several mitigating factors for drug involvement. The most "
                "relevant for a recent graduate who used marijuana in college is that the "
                "use was experimental in nature, has not recurred, and occurred before "
                "the individual was applying for or holding a clearance. Adjudicators look "
                "at recency: use that stopped two or more years ago and has not recurred "
                "is treated very differently from recent use. They also consider frequency: "
                "occasional experimentation is viewed differently from habitual use.\n\n"
                "Two things are critical under Guideline H. First, full disclosure on the "
                "SF-86 is essential — the form asks about past drug use, and deliberate "
                "omissions are a Guideline E concern that compounds the underlying issue. "
                "Second, and the ADR is explicit about this: adjudicators will ask whether "
                "you intend to use marijuana in the future. If you are pursuing a federal "
                "security clearance, a straightforward commitment not to use illegal "
                "substances going forward — and following through on that commitment — "
                "is the clearest mitigating factor available to you.\n\n"
                "If you participated in any drug treatment or counseling, even informally, "
                "that is a positive indicator, not a negative one. Voluntary action to "
                "address a substance concern is consistently treated as mitigating by "
                "the ADR."
            ),
        }),
        "interview_prep": (
            "# Subject Interview Preparation Guide\n"
            "**Session: Entry-Level SECRET — New Graduate**\n\n"
            "---\n\n"
            "## What Is a Subject Interview?\n\n"
            "A Subject Interview (sometimes called an Investigative Interview) is a "
            "structured conversation with a background investigator — typically an "
            "employee of the Defense Counterintelligence and Security Agency (DCSA) "
            "or a contractor investigator. It is not an interrogation. It is an "
            "opportunity for the investigator to clarify information on your SF-86, "
            "gather context that the form cannot capture, and give you a chance to "
            "explain any issues in your background.\n\n"
            "Investigators are trained to be thorough but professional. You are "
            "expected to be honest, forthright, and complete. The interview typically "
            "covers the same areas as the SF-86, with follow-up questions on anything "
            "that needs clarification.\n\n"
            "---\n\n"
            "## What to Expect\n\n"
            "- The investigator will open by explaining the purpose and asking you to "
            "verify your identity\n"
            "- Questions follow a structured format tied to the adjudicative guidelines\n"
            "- You may be asked to sign a release or clarify documents\n"
            "- The interview may last 1-3 hours depending on complexity\n"
            "- Being thorough and honest is more important than being brief\n\n"
            "---\n\n"
            "## Guideline E — Personal Conduct: Topics Investigators May Explore\n\n"
            "- Investigators may ask you to walk through your employment history and "
            "explain any gaps\n"
            "- Investigators may ask about any terminations or performance issues at "
            "prior employers\n"
            "- Investigators may ask whether all information on the SF-86 is complete "
            "and accurate, and give you an opportunity to add anything you may have "
            "omitted\n"
            "- Investigators may ask about any civil court actions, judgments, or "
            "restraining orders\n"
            "- If there were omissions on the SF-86, investigators may ask why "
            "information was not included and whether the omission was intentional\n\n"
            "---\n\n"
            "## Guideline F — Financial Considerations: Topics Investigators May Explore\n\n"
            "- Investigators may ask about your outstanding debts, including student loans, "
            "and whether they are current\n"
            "- Investigators may ask whether any accounts are in delinquency or collections\n"
            "- If there have been financial difficulties, investigators may ask about the "
            "circumstances that led to them and what steps you have taken to resolve them\n"
            "- Investigators may ask about your current financial situation and whether "
            "you are able to meet your obligations\n\n"
            "---\n\n"
            "## Guideline H — Drug Involvement: Topics Investigators May Explore\n\n"
            "- Investigators may ask about any use of illegal substances, including "
            "marijuana, and when you last used them\n"
            "- Investigators may ask about the frequency and circumstances of any past use\n"
            "- Investigators may ask whether you have used any prescription drugs not "
            "prescribed to you\n"
            "- Investigators may ask whether you intend to use marijuana or other illegal "
            "substances in the future (federal law applies regardless of state law)\n"
            "- If you participated in any drug counseling or treatment, investigators may "
            "ask about that as well\n\n"
            "---\n\n"
            "## General Advice for the Interview\n\n"
            "**Be honest and complete.** The most important thing you can do in a Subject "
            "Interview is be forthright. Investigators are trained to detect inconsistencies, "
            "and attempting to minimize or omit information typically makes things worse. "
            "If you are unsure about a detail, say so honestly.\n\n"
            "**Context matters.** Don't just answer yes or no to sensitive questions — "
            "explain the circumstances. A financial difficulty caused by a medical "
            "emergency tells a very different story than ongoing irresponsibility.\n\n"
            "**Consult an attorney if you have significant concerns.** This guide is "
            "educational preparation, not legal advice. If you have complex issues in your "
            "background — criminal history, significant financial problems, or foreign "
            "contacts — consulting a security clearance attorney before your interview "
            "is strongly recommended."
        ),
        "is_demo": True,
    },
    {
        "id": 2,
        "session_name": "Senior TS/SCI — Foreign Contacts",
        "clearance_level": "TOP SECRET / SCI",
        "guidelines_selected": json.dumps(["B", "C", "L"]),
        "context_notes": (
            "Senior scientist applying for TS/SCI. Born in Taiwan, naturalized U.S. citizen. "
            "Parents still live in Taiwan. Has a Taiwanese passport that recently expired. "
            "Has collaborated professionally with researchers at Chinese universities."
        ),
        "claude_briefings": json.dumps({
            "B": (
                "**Guideline B — Foreign Influence**\n\n"
                "Foreign Influence is one of the most carefully evaluated guidelines for "
                "individuals with significant international backgrounds, and for a naturalized "
                "citizen with family abroad and professional contacts in foreign countries, "
                "it is almost certain to receive detailed attention. Understanding what "
                "adjudicators are trained to look for — and what the ADR says mitigates "
                "those concerns — is essential preparation.\n\n"
                "The core question Guideline B asks is not 'do you have foreign contacts?' "
                "Everyone has a personal history and an international network. The question "
                "is: 'do any of those contacts create a vulnerability that could be exploited "
                "to compromise your judgment or your access to classified information?' "
                "The concern is coercion, not connection.\n\n"
                "Family members who reside abroad receive particular attention — not because "
                "having a parent in Taiwan is inherently problematic, but because a family "
                "member who could be pressured, threatened, or used as leverage creates a "
                "potential vulnerability. Adjudicators are trained to consider whether that "
                "vulnerability is real and whether it can be mitigated. The ADR identifies "
                "several mitigating factors: if the contact cannot realistically be used as "
                "a basis for exploitation, if the relationship is one that the government "
                "is aware of and can account for, or if the family member has no connection "
                "to a foreign government.\n\n"
                "Professional contacts with researchers at foreign universities — including "
                "Chinese universities — are a different kind of concern. The ADR focuses on "
                "whether such contacts could create exploitation risk, particularly if those "
                "individuals are in positions that could be leveraged by a foreign intelligence "
                "service. Adjudicators will want to understand the nature of the collaboration: "
                "was it published academic research? Was classified information anywhere near "
                "the collaboration? Were the contacts known or suspected to have intelligence "
                "affiliations? Routine academic collaboration documented in the open literature "
                "looks very different from undisclosed contacts with someone who has government "
                "affiliation.\n\n"
                "The most important mitigation under Guideline B is proactive disclosure and "
                "transparency. If contacts and family members are reported, discussed openly, "
                "and the government can assess them, the vulnerability is substantially reduced. "
                "Failure to disclose, by contrast, creates a Guideline E issue that compounds "
                "the original concern."
            ),
            "C": (
                "**Guideline C — Foreign Preference**\n\n"
                "Guideline C addresses acts that suggest an individual may prefer a foreign "
                "country's interests over those of the United States. For a naturalized U.S. "
                "citizen who retains citizenship or travel documents from another country, "
                "this guideline requires careful attention — not because dual nationality "
                "is automatically disqualifying, but because certain actions associated with "
                "it can be.\n\n"
                "The critical distinction in Guideline C is between passive dual citizenship "
                "(which is common and generally not disqualifying) and the active exercise "
                "of rights or obligations associated with that citizenship in ways that "
                "conflict with U.S. obligations. The ADR identifies several specific actions "
                "that adjudicators are trained to evaluate: accepting and using a foreign "
                "passport, voting in a foreign election, or serving in a foreign military "
                "without U.S. government sanction.\n\n"
                "A Taiwanese passport that has expired is an important detail. The question "
                "adjudicators are trained to ask is not whether the passport exists — many "
                "naturalized citizens have or had foreign passports — but whether it was "
                "used after naturalization and under what circumstances. Use of a foreign "
                "passport after becoming a U.S. citizen is more concerning than possessing "
                "an expired one. If the passport was used for travel to countries that would "
                "not accept a U.S. passport, or for work purposes, the ADR describes these "
                "as potential mitigating factors.\n\n"
                "The clearest mitigation for Guideline C is expressed commitment to U.S. "
                "citizenship and, where applicable, renunciation of the foreign citizenship "
                "or surrender of the foreign passport. Where renunciation is not feasible "
                "or not required, a clear and documented statement of intent, combined with "
                "the absence of actions indicating foreign preference, is generally sufficient. "
                "The ADR is explicit that dual citizenship acquired automatically at birth "
                "or through marriage — rather than affirmatively sought — is treated with "
                "less concern than citizenship actively pursued."
            ),
            "L": (
                "**Guideline L — Outside Activities**\n\n"
                "Outside Activities addresses whether outside employment, organizational "
                "memberships, or other non-work activities create conflicts of interest or "
                "suggest misplaced loyalties. For a senior scientist with international "
                "professional collaborations, the specific sub-concern under this guideline "
                "is service to or financial relationships with foreign entities.\n\n"
                "Academic and professional collaboration in the sciences is normal and, in "
                "most cases, not a concern under Guideline L. Published research with "
                "international co-authors, attendance at international conferences, and "
                "peer review of foreign researchers' work are routine activities that "
                "adjudicators understand and do not automatically raise under this guideline. "
                "What adjudicators are trained to look for is whether an outside activity "
                "creates a financial or loyalty obligation to a foreign entity that could "
                "conflict with the applicant's duty to protect classified information.\n\n"
                "The specific concerns that might arise for a senior scientist include: "
                "receiving compensation from a foreign university or government (consulting "
                "fees, grants paid directly to the individual, honoraria), serving on a "
                "foreign institution's advisory board with formal obligations, or participation "
                "in programs that have foreign government funding and direction. Pure academic "
                "collaboration — co-authoring a paper, sharing data through normal channels, "
                "attending workshops — looks quite different from having a formal employment "
                "or financial relationship with a foreign institution.\n\n"
                "The ADR emphasizes transparency here as the key mitigation. Activities that "
                "are publicly known, documented in published research, and reported through "
                "normal security channels are treated very differently from undisclosed "
                "financial relationships. If you have received any foreign funding, grants, "
                "or compensation — even small honoraria — be prepared to disclose and explain "
                "those in detail. The disclosure itself is the most important step."
            ),
        }),
        "interview_prep": (
            "# Subject Interview Preparation Guide\n"
            "**Session: Senior TS/SCI — Foreign Contacts**\n\n"
            "---\n\n"
            "## What Is a Subject Interview?\n\n"
            "For a TS/SCI investigation, the Subject Interview is typically more in-depth "
            "than for a Secret clearance investigation. The investigator will cover your "
            "full background in detail, with particular attention to areas where the "
            "investigation has developed questions. For an applicant with international "
            "background and professional contacts, the interview will almost certainly "
            "focus substantially on Guidelines B, C, and L.\n\n"
            "---\n\n"
            "## Guideline B — Foreign Influence: Topics Investigators May Explore\n\n"
            "- Investigators may ask for a detailed accounting of your family members "
            "who reside outside the United States, including their employment and any "
            "government affiliations\n"
            "- Investigators may ask about the nature and frequency of your contact "
            "with those family members\n"
            "- Investigators may ask about professional contacts you maintain with "
            "individuals in foreign countries, and whether any of those individuals "
            "hold government positions or university affiliations that could connect "
            "them to foreign intelligence services\n"
            "- Investigators may ask whether anyone has ever approached you to share "
            "information about your work, your employer, or U.S. programs\n"
            "- Investigators may ask whether you believe any of your foreign contacts "
            "could be used as leverage against you\n\n"
            "---\n\n"
            "## Guideline C — Foreign Preference: Topics Investigators May Explore\n\n"
            "- Investigators may ask about any citizenship you hold or have held in "
            "any country other than the United States\n"
            "- Investigators may ask whether you have held or used a foreign passport, "
            "and if so, when and under what circumstances\n"
            "- Investigators may ask about participation in any foreign elections\n"
            "- Investigators may ask about your views regarding your country of origin "
            "and your commitment to the United States\n"
            "- If you hold an expired foreign passport, investigators may ask whether "
            "you intend to renew it\n\n"
            "---\n\n"
            "## Guideline L — Outside Activities: Topics Investigators May Explore\n\n"
            "- Investigators may ask about all professional collaborations with foreign "
            "institutions, including universities\n"
            "- Investigators may ask whether you have received any compensation, grants, "
            "or honoraria from foreign entities\n"
            "- Investigators may ask whether you serve on any advisory boards or "
            "review panels for foreign institutions\n"
            "- Investigators may ask whether any of your outside professional activities "
            "create any financial ties to foreign entities\n\n"
            "---\n\n"
            "## General Advice\n\n"
            "**Prepare a thorough accounting of all foreign contacts.** For a TS/SCI "
            "investigation with your background, investigators will expect you to know "
            "your own foreign contacts well and be able to discuss them in detail. "
            "Making a list of key contacts, their institutions, and the nature of your "
            "relationship before the interview will help you be complete.\n\n"
            "**Consult a security clearance attorney.** Given the complexity of your "
            "background — foreign family members, professional contacts in China, and "
            "a prior foreign passport — consulting a security clearance attorney before "
            "your investigation is strongly recommended. This guide is educational "
            "preparation, not legal advice."
        ),
        "is_demo": True,
    },
    {
        "id": 3,
        "session_name": "Reinstatement — Alcohol and Criminal Record",
        "clearance_level": "SECRET",
        "guidelines_selected": json.dumps(["G", "J", "E"]),
        "context_notes": (
            "Prior clearance lapsed. Applying for reinstatement. Has a 7-year-old DUI "
            "that resulted in a conviction. Completed alcohol counseling. Has been sober "
            "for 5 years. No subsequent incidents."
        ),
        "claude_briefings": json.dumps({
            "G": (
                "**Guideline G — Alcohol Consumption**\n\n"
                "Guideline G addresses whether alcohol use rises to a level suggesting "
                "problematic lack of self-control, impaired judgment, or unreliability. "
                "The guideline is not about moderate social drinking — adjudicators are "
                "specifically looking for patterns of excessive use, alcohol-related "
                "incidents, and whether alcohol dependence affects professional reliability.\n\n"
                "For someone with a prior DUI conviction and a documented history of "
                "alcohol-related concerns, understanding how the ADR frames this "
                "guideline — and what it says about rehabilitation — is critical. "
                "The ADR is explicit that the goal is not to disqualify people who once "
                "had a problem with alcohol; the goal is to assess whether that problem "
                "is in the past and whether current behavior reflects reliability and "
                "self-control.\n\n"
                "The ADR identifies several mitigating factors that are directly relevant "
                "to a reinstatement situation with prior alcohol concerns. The most "
                "important are: the alcohol problem is in the past and there is no recent "
                "abuse; the individual voluntarily sought and completed treatment; there "
                "have been no alcohol-related incidents in a substantial period; and a "
                "credentialed professional has provided a favorable prognosis. A five-year "
                "period of sobriety following completed counseling is precisely the kind "
                "of demonstrated, sustained rehabilitation the ADR describes as mitigating.\n\n"
                "One nuance worth understanding: the ADR mentions coworker and supervisor "
                "assessments. In a reinstatement investigation, references will likely be "
                "asked about your reliability and whether they have observed any alcohol-related "
                "behavior. Colleagues who can speak to your current professionalism and "
                "reliability are an important part of the picture.\n\n"
                "If you participated in any formal program — Alcoholics Anonymous, outpatient "
                "treatment, an Employee Assistance Program — those are positive indicators, "
                "not liabilities. Voluntary engagement with treatment is explicitly called "
                "out in the ADR as a mitigating factor. Be prepared to provide documentation "
                "of treatment completion if available."
            ),
            "J": (
                "**Guideline J — Criminal Conduct**\n\n"
                "Criminal Conduct addresses whether a criminal history indicates poor judgment, "
                "disregard for the law, or untrustworthiness. The guideline is not a binary "
                "disqualifier based on conviction alone — adjudicators weigh the nature of the "
                "offense, how long ago it occurred, and the evidence of rehabilitation since.\n\n"
                "A DUI conviction carries two dimensions under Guideline J. First, it is a "
                "criminal conviction that adjudicators will note. Second, it connects directly "
                "to Guideline G (Alcohol Consumption) because it is an alcohol-related "
                "incident. The ADR treats these together when they arise from the same pattern "
                "of behavior, which means that mitigating factors under Guideline G can also "
                "inform how adjudicators view the Guideline J concern.\n\n"
                "The specific mitigating factors the ADR describes for criminal conduct are "
                "directly applicable here. The offense was isolated — a single DUI, not a "
                "pattern of criminal behavior. It occurred seven years ago — the ADR consistently "
                "treats recency as a key factor; an offense from many years ago is weighted "
                "very differently than a recent one. Most importantly, there is substantial "
                "evidence of rehabilitation: completed counseling, five years of sobriety, "
                "and no subsequent incidents of any kind.\n\n"
                "The ADR's description of favorable Criminal Conduct outcomes closely matches "
                "this profile: an isolated incident in the past, no pattern, demonstrated "
                "rehabilitation, and a record of law-abiding behavior since. The passage of "
                "time combined with affirmative rehabilitation is the strongest possible "
                "posture under this guideline.\n\n"
                "One practical note: the SF-86 asks about DUI convictions specifically. "
                "Disclose it completely and accurately, including the state, date, and "
                "outcome. If the conviction was expunged, the form's instructions govern "
                "whether to disclose it — some SF-86 questions explicitly ask about "
                "expunged records. Read the instructions for each question carefully rather "
                "than assuming expungement means non-disclosure."
            ),
            "E": (
                "**Guideline E — Personal Conduct**\n\n"
                "For a reinstatement application, Guideline E takes on a specific dimension "
                "beyond its general application: it focuses on how honestly and completely "
                "you report the prior alcohol and criminal history, and whether your conduct "
                "in the security process itself reflects integrity.\n\n"
                "The ADR is explicit that adjudicators evaluate whether a person is forthright "
                "with investigators and whether they accurately represent their background. "
                "In a reinstatement context, there may be a temptation to minimize prior "
                "issues — to describe the DUI as 'a minor traffic incident' rather than a "
                "criminal conviction, or to underreport the extent of prior alcohol use. "
                "Adjudicators are experienced with these presentations, and the investigation "
                "will independently develop facts. Inconsistencies between what you report "
                "and what the investigation finds are a Guideline E concern that can be more "
                "damaging than the underlying issue itself.\n\n"
                "The strongest possible posture under Guideline E for this type of reinstatement "
                "is straightforward disclosure combined with a clear, factual account of what "
                "happened and what has changed. 'I had a DUI seven years ago. I recognized "
                "that alcohol was a problem. I completed counseling and have not had a drink "
                "in five years. Here is the documentation.' That narrative — honest, complete, "
                "and supported by evidence — is exactly what the ADR describes as the foundation "
                "of favorable Personal Conduct review.\n\n"
                "The ADR also notes that proactive correction of prior omissions is mitigating. "
                "If there is anything in your prior investigation or clearance history that "
                "was not fully disclosed, the reinstatement process is the moment to be "
                "complete. Proactive disclosure is treated much more favorably than discovery "
                "of a previously concealed fact."
            ),
        }),
        "interview_prep": (
            "# Subject Interview Preparation Guide\n"
            "**Session: Reinstatement — Alcohol and Criminal Record**\n\n"
            "---\n\n"
            "## What Is a Subject Interview?\n\n"
            "A reinstatement investigation covers your background since your last clearance "
            "lapsed. The investigator will review your updated SF-86, ask about changes in "
            "your circumstances, and specifically explore any issues that may have developed "
            "in the intervening period — including the DUI conviction and your alcohol history.\n\n"
            "For a reinstatement with prior issues, the Subject Interview gives you the "
            "opportunity to tell your rehabilitation story directly. Investigators are "
            "trained to assess current risk, not just past incidents, and a well-prepared, "
            "honest account of what happened and how you addressed it is your strongest asset.\n\n"
            "---\n\n"
            "## Guideline G — Alcohol Consumption: Topics Investigators May Explore\n\n"
            "- Investigators may ask about the circumstances surrounding your prior alcohol use\n"
            "- Investigators may ask about the counseling you completed — when, where, "
            "what it involved, and the outcome\n"
            "- Investigators may ask about your current relationship with alcohol and "
            "whether you are currently drinking\n"
            "- Investigators may ask whether you have attended any ongoing support programs\n"
            "- Investigators may ask references and former colleagues whether they have "
            "observed any alcohol-related behavior\n\n"
            "---\n\n"
            "## Guideline J — Criminal Conduct: Topics Investigators May Explore\n\n"
            "- Investigators may ask for a detailed account of the DUI — the date, "
            "circumstances, jurisdiction, and outcome\n"
            "- Investigators may ask about the conviction record and any other criminal "
            "history, including anything not on your SF-86\n"
            "- Investigators may ask whether you have had any other law enforcement contact "
            "since the DUI\n"
            "- Investigators may ask what steps you took after the conviction\n\n"
            "---\n\n"
            "## Guideline E — Personal Conduct: Topics Investigators May Explore\n\n"
            "- Investigators may ask whether you disclosed the DUI on your prior SF-86 "
            "and on the current one\n"
            "- Investigators may ask whether there are any other incidents from your "
            "history that you want to add or clarify\n"
            "- Investigators may ask about your employment history since the lapse\n\n"
            "---\n\n"
            "## General Advice\n\n"
            "**Tell your rehabilitation story clearly.** Five years of sobriety following "
            "completed counseling is a genuinely strong mitigation record. Be prepared to "
            "state the facts clearly: when the problem was at its worst, what you did to "
            "address it, and what your life looks like now. The investigator's job is to "
            "assess current risk — help them see the full picture.\n\n"
            "**Bring documentation if you have it.** Completion certificates from counseling "
            "programs, reference letters from treatment providers, or other documentation "
            "of your rehabilitation can support your account.\n\n"
            "**Consult a security clearance attorney.** This guide is educational preparation, "
            "not legal advice. Given the complexity of a reinstatement with prior issues, "
            "consulting a security clearance attorney is strongly recommended."
        ),
        "is_demo": True,
    },
]


def seed_demo_sessions(db_session) -> None:
    """Insert the three demo sessions if they do not already exist."""
    from models import Session

    for s in DEMO_SESSIONS:
        exists = db_session.query(Session).filter_by(id=s["id"]).first()
        if not exists:
            session = Session(
                id=s["id"],
                session_name=s["session_name"],
                clearance_level=s["clearance_level"],
                guidelines_selected=s["guidelines_selected"],
                context_notes=s["context_notes"],
                claude_briefings=s["claude_briefings"],
                interview_prep=s["interview_prep"],
                is_demo=s["is_demo"],
            )
            db_session.add(session)
    db_session.commit()
